### ISSUE TITLE
JavaScript runtime error: Assignment to read-only properties is not allowed in strict mode

### ISSUE THREAD

**Issue by usman-aziz** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms-App#48]
This issue was originally raised via forum topic:
[https://forum.groupdocs.com/t/modern-front-end-on-internet-explorer/5788/5](https://forum.groupdocs.com/t/modern-front-end-on-internet-explorer/5788/5)

When running the application in Internet Explorer 11, we get an unhandled exception on line 531 of app.js saying "_JavaScript runtime error: Assignment to read-only properties is not allowed in strict mode_". We get rid of the exception when changing the assignment method from: 
`element[0].style = "height:" + parseInt(height) + "px!important; width:100%!important; ";`
to:
`element[0].setAttribute("style", "height:" + parseInt(height) + "px!important; width:100%!important; ");`
However, with this change, the zoom feature stops working. Please check.

**Comment by AamirWaseem** [comment]
@usmanazizgroupdocs

Thank you for sharing the details.

Please use "**.style.cssText =** " instead of "**.style =** " for all occurrences in "**/Content/App.js**". We have updated source code with same solution. You can also get latest version and tryout the fix.
