### ISSUE TITLE
The zoom feature is not working in IE 11

### ISSUE THREAD

**Issue by usman-aziz** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms-App#49]
This issue was originally raised via forum topic:
[https://forum.groupdocs.com/t/modern-front-end-on-internet-explorer/5788/5](https://forum.groupdocs.com/t/modern-front-end-on-internet-explorer/5788/5)

The zoom feature is not working in IE 11.

**Comment by mlasarga** [comment]
Hi there!!!
Any news about this issue?
We are waiting to deploy last version.

Best regards

**Comment by usman-aziz** [comment]
@mlasarga,

Thanks for coming back to us.

It is expected that the fix of this issue will be available by the end of the next week. However, the provided ETA is not guaranteed. We shall keep you informed in case of any updates.

**Comment by mlasarga** [comment]
Hello, how are you?
Any news? 
Do we have a new release or fix?

Best regards

**Comment by usman-aziz** [comment]
@mlasarga,

Your reported issue has been fixed. However, the fixed version of the application is expected to be released at the beginning of the next week. We shall keep you informed in case of any updates.

**Comment by mrimoli** [comment]
Hello, any news of the release of this fix?

**Comment by usman-aziz** [comment]
@mrimoli ,

Thanks for coming back to us. The fix of your reported issue was expected to be released in the current week, however, the release is delayed because of some blocking issues. We are trying our best to minimize the further delay. We apologize for the inconvenience and appreciate your cooperation in this regard. We shall keep you notified in case of any updates.
