### ISSUE TITLE
Issue when viewing tiff image

### ISSUE THREAD

**Issue by usman-aziz** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms-App#52]
This issue was originally raised via forum topic:
[https://forum.groupdocs.com/t/rendering-multi-tiff-issues/5966](https://forum.groupdocs.com/t/rendering-multi-tiff-issues/5966)

When loading a tiff image in the viewer, the image appears too big to fit in the screen (see [screenshot](https://imgur.com/QSNROTU)). If we select "Fit to width" zoom option, the image becomes more big and horizontal scroll appears. The sample tiff file can be found in the above-mentioned topic.

**Comment by mlasarga** [comment]
Hi there!!!
Any news about this issue?
We are waiting to deploy last version.

Best regards

**Comment by usman-aziz** [comment]
@mlasarga,

Thanks for coming back to us.

It is expected that the fix of this issue will be available by the end of the next week. However, the provided ETA is not guaranteed. We shall keep you informed in case of any updates.

**Comment by mlasarga** [comment]
Hello, how are you?
Any news? 
Do we have a new release or fix?

Best regards

**Comment by usman-aziz** [comment]
@mlasarga,

Your reported issue has been fixed. However, the fixed version of the application is expected to be released at the beginning of the next week. We shall keep you informed in case of any updates.
