### ISSUE TITLE
Issue when downloading tiff file as PDF

### ISSUE THREAD

**Issue by usman-aziz** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms-App#53]
This issue was originally raised via forum topic:
[https://forum.groupdocs.com/t/scrooll-and-is-displayed-incorrectly/5965](https://forum.groupdocs.com/t/scrooll-and-is-displayed-incorrectly/5965)

When downloading the tiff file as PDF using the download options provided in the application, we get the following issues:

- Chrome: https://imgur.com/YHB0Mad
- IE 11: https://imgur.com/bPuTYgi

The problematic tiff file can be downloaded from the above-mentioned forum topic.

**Comment by mlasarga** [comment]
Hi there!!!
Any news about this issue?
We are waiting to deploy last version.

Best regards

**Comment by usman-aziz** [comment]
@mlasarga,

Thanks for coming back to us.

It is expected that the fix of this issue will be available by the end of the next week. However, the provided ETA is not guaranteed. We shall keep you informed in case of any updates.

**Comment by mlasarga** [comment]
Hello, how are you?
Any news? 
Do we have a new release or fix?

Best regards

**Comment by usman-aziz** [comment]
@mlasarga,

Your reported issue has been fixed. However, the fixed version of the application is expected to be released at the beginning of the next week. We shall keep you informed in case of any updates.

**Comment by usman-aziz** [comment]
@mlasarga ,

The issue has been fixed. Please download the updated version of the application from [here](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms-App).
